### PR TITLE
Update wiselib.stable/external_interface/shawn/shawn_radio.h

### PR DESCRIPTION
**Pull request by shubhamsomani**
Added functionality to make your own radio that supports unregister functionality

### CODE REVIEW

**Comment by Droggelbecher** [comment]
I'm not sure, what exactly this does / what it is good for, could you elaborate?

**Comment by shubhamsomani** [comment]
Umm....these functions are for adding register & unregister facility. The typedefed struct can be instantiated by the protocol that registers for callbacks. And the unregister functionality is used to erase the registered struct.
Is something wrong in my understanding?

**Comment by Droggelbecher** [comment]
Sorry, I still don't understand. You did not implement unreg_recv_callback but instead added two new functions that are not part of the radio concept and use a parameter type that is inherently specific to the shawn radio.
I dont see what - conceptually - an object of type "s" is, why does it hold a pointer to a shawn os? But - at least from the perspective of a process' code - there should only be ever one shawn os object of interest (ie os()).
What is the purpose of the also peculiar named members "flag" and "ID"?
Also the registered things - whatever they may represent - do not seem to interact with anything at all except for registering and unregistering. Whats the point of registering something then?

**Comment by Droggelbecher** [comment]
Besides, I doubt your code does even compile, as I dont believe receivers.ID.find (where receivers is a vector_static) is a valid expression

**Comment by shubhamsomani** [comment]
Sorry for "receivers.ID.find". My mistake.
I have reviewed my code and I suppose this http://pastebin.com/vgiDRQfF should work.
The struct s is supposed to store the object pointer and the id of the process. A vector of structs is made to store all the processes registering for callbacks. So when a process wants to unregister  we find the id of the process and erase it from the vector list.
ps-
Please suggest the correct syntax for line 120. Thanks for pointing out the errors :)

**Comment by Droggelbecher** [comment]
I will close this pull request now, feel free to create a new one when when the code is working and thoroughly tested.

**Comment by shubhamsomani** [comment]
I have my code working and have tested it too . http://ideone.com/x0c9TB. Should I create a new pull request now?

**Comment by Droggelbecher** [comment]
I think line 114 still contains an error, also i dont understand why you set ID=os().proc->id(), that would mean each registered callback gets the same id which doesn't seem to make much sense to me.

**Comment by shubhamsomani** [comment]
I returned os().proc->id() so that the id could be used while calling the unregister function.

You are correct that it would lead to getting the same id for each callback..(I did it because I was short of ideas...what should i do to automate the id generation?
1) Should I make an random unique value generator to assign id's 
OR 
2) should I leave the ID generation to the user , he can instantiate the typedefed struct and pass it as a parameter in the reg_recv method ?)

**Comment by konstantinosch** [comment]
We have already discussed about this... There is no rationale for automated
ID assignment as it has to include dupe checks.

As I previously said, make sure you maintain old functionality and test
this implementation with a notify_receivers call.

I still don't understand whether this is an upgrade, new radio, or compete
replacement. Also in order for this to work you have to show progress with
fully working protocol setup. Like a routing scheme that uses this radio
after registration and stops receiving callbacks after de_registration etc.

So in order to get more concrete answers, show more concrete progress :)

Sent from my iPhone

On Feb 26, 2013, at 16:20, Shubham Somani notifications@github.com wrote:

I returned os().proc->id() so that the id could be used while calling the
unregister function.

You are correct that it would lead to getting the same id for each
callback..(I did it because I was short of ideas...what should i do to
automate the id generation?
1) Should I make an random unique value generator to assign id's
OR
2) should I leave the ID generation to the user , he can instantiate the
typedefed struct and pass it as a parameter in the reg_recv method ?)

—
Reply to this email directly or view it on
GitHubhttps://github.com/ibr-alg/wiselib/pull/35#issuecomment-14119795
.

**Comment by shubhamsomani** [comment]
I'm trying to upgrade the unregister functionality. This http://pastebin.com/aeaDPMmz is the working protocol setup.
But since the id generated is same from http://pastebin.com/7F29uGZu it unregisters only one node.

**Comment by konstantinosch** [comment]
I think you don't understand entirely the way registration works. Nodes
don't register. Nodes can include various online protocols that communicate
with each other effectively through registered callbacks. From custom
radios to routing to security protocols... The unregistration functionality
is trivial compared to the general idea of using this library. My advise is
to focus on your specific algorithmic implementation for WSN. Not this.

You have also been provided with examples already with full functionality
for you seek to see and have been given enough feedback to do this.

We are definitely aware of the lack of unregistration for callbacks.

Kostas

Sent from my iPhone

On Feb 28, 2013, at 14:22, Shubham Somani notifications@github.com wrote:

I'm trying to upgrade the unregister functionality. This
http://pastebin.com/aeaDPMmz is the working protocol setup.
But since the id generated is same from http://pastebin.com/7F29uGZu it
unregisters only one node.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ibr-alg/wiselib/pull/35#issuecomment-14232858
.

**Comment by shubhamsomani** [comment]
ok :/

**Pull request closed without merging**
