### PR TITLE
Multiple parallel timers implemented using MsTimer2 library

### PR DESCRIPTION
**Pull request by parita**
The MsTimer2 uses interrupts to implement timer events. Defined a timer queue for Arduino Timers along with a tested example app which works on the device.

### CODE REVIEW

**Comment by Droggelbecher** [comment]
Hey Parita.
Nice work, I wonder though: It seems you copy-pasted the priority queue code instead of using it?
Was there a specific reason for that?

**Comment by parita** [comment]
The only minor change I made was to the compare function - the reason being that I needed the queue to prioritize as per the event_time variable only. priority_queue_dynamic let me define a compare function of my own and hence I tried using that. priority_queue seems to be prioritizing the elements as per the values itself.

**Comment by Droggelbecher** [comment]
Hm i think that is not a problem as you can just implement different comparision operators for your event_time struct, like so:

``` c++

struct arduino_timer_item {
  bool operator<(const arduino_timer_item& other) { return event_time < other.event_time; }
  bool operator==(const arduino_timer_item& other) { return event_time == other.event_time; }

  // we can define the rest of comparison operators by using the two above
  bool operator!=(const arduino_timer_item& other) { return !(*this == other); }
  bool operator>(...) { return (*this != other) && !(*this < other); }
  bool operator<=(...) { return (*this < other) || (*this == other); }
  bool operator>=(...) { return (*this > other) || (*this == other); }
};
```

**Comment by parita** [comment]
Oh okay, thanks ! I'll make the changes accordingly then. I could also get the code running without the need of MsTimer2 library. So will integrate this into it.

**Pull request merged**
